[package]
name = "cnmplayer"
version = "0.3.2"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
log = "0.4"
env_logger = "0.11"
libc = "0.2"
ratatui = "0.30"
crossterm = "0.29"
directories = "6"
tokio = { version = "1", features = ["full"] }
ncm-api = { path = "./ncm-api-rs" }
qrcode = "0.14"
image = "0.25"
reqwest = { version = "0.13", default-features = false, features = ["rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
unicode-width = "0.2"
rodio = "0.22"
symphonia = { version = "0.5", features = ["aac", "alac", "flac", "isomp4", "mp3", "ogg", "wav", "vorbis"] }
lofty = "0.24"
base64 = "0.22"
ureq = { version = "3", features = ["json"] }
chromaprint = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2.0"
alsa = "0.11"
mpris-server = "0.9"

[profile.release]
codegen-units = 1
lto = true
