[package]
name = "cnmplayer"
version = "0.4.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
log = "0.4"
env_logger = "0.11"
libc = "0.2"
ratatui = { version = "0.30", default-features = false, features = ["crossterm", "layout-cache"] }
ratatui-image = { version = "10", default-features = false, features = ["crossterm", "chafa-dyn"] }
crossterm = "0.29"
directories = "6"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
ncm-api = { path = "./ncm-api-rs" }
qrcode = "0.14"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
unicode-width = "0.2"
rodio = { git = "https://github.com/RustAudio/rodio", default-features = false, features = ["playback", "symphonia"] }
cpal = { git = "https://github.com/RustAudio/cpal", features = ["pipewire"] }
lofty = "0.24"
base64 = "0.22"
ureq = { version = "3", features = ["json"] }
chromaprint = "0.2"

# 标准 较高 极高 mp3
# 无损 Hi-Res 高清环绕声 flac !VIP
# 沉浸环绕声 杜比全景声 超清母带 flac !SVIP
symphonia = { version = "0.5", default-features = false, features = ["mp3", "flac"] }

[target.'cfg(target_os = "linux")'.dependencies]
alsa = "0.11"
mpris-server = "0.9"

[profile.release]
codegen-units = 1
lto = true
strip = true
